### PR TITLE
Major Updates

### PR DESCRIPTION
**Pull request by konsumer**
I improved the README a bit:
* nicer looking formula
* clearer instructions

improved interface
* only 2 functions
* now training can be saved

improved unit tests
* show off loading model
* simple

added build/publish tools:
* babel for ES6, so the lib supports older node versions
* scripts to make building/publishing tasks easier

If you accept the PR, do this to publish update on npm:

```
npm version major # increment the major number in tag and package.json, this release has breaking changes
npm publish # send to npm
```

### CODE REVIEW

**Comment by konsumer** [comment]
Hmm, it seems like commit 0a15a87 changed the outcome pretty dramatically. Maybe I am not adding 1 to the counts (mentioned at end of video to account for 0's) in the right place?

**Comment by konsumer** [comment]
Any ideas on the "add 1" issue?

Without adding 1, I get roughly the same numbers you got:

old:
```
no: 0.42163100057836905
yes: 0.578368999421631
```

new:
```
no: 0.5713725874399922
yes: 0.42862741256000775,
```

which basically reverses the prediction.

The code in question is [here](https://github.com/kermitt/NaiveBayes_js/blob/master/src/Bayes.js#L59).

**Comment by kermitt** [comment]
Yeah...

Wow - flipflop is dramatic...

Well, the purpose of the 'add 1 to everything' is to prevent any possible
'divide by zero' issues.
So, let us add a minimum 0.0000001 to everything...   i.e., the smallest
thing more than zero.
That will serve to prevent that division issue but it will not add much
noise to the overall operation.

**Comment by konsumer** [comment]
That is a great solution. I think js can do much smaller numbers, but that is a good start. Why not `Number.MIN_VALUE`? In the case of my browser, it's `5e-324`

**Pull request merged**
